### PR TITLE
Fix #35 - Using 'Gulp+Browserify' to build gtfs-validator-webap instead of 'Component'

### LINKED ISSUE #35: Using 'Gulp+Browserify' to build gtfs-validator-webapp instead of 'Component'
@sheldonabrown @laidig We are currently using gtfs-validator-webapp in https://github.com/CUTR-at-USF/gtfs-realtime-validator project. Using `component` to build gtfs-validator-webapp is causing to have some restrictions on build process. I do also remember laidig mentioning about switching to another build process as 'Component' is deprecated. So, if this is okay, we would like to make changes to the build process of gtfs-validator-webapp to use `Gulp+Browserify`. 
Cc'd @barbeau

### PR DESCRIPTION
**Pull request by mohangandhiGH**
Fixes #35 
@barbeau @sheldonabrown @laidig Changes to build using gulp and browserify.

### CODE REVIEW

**Comment by laidig** [comment]
I believe you need to update the readme (component -> gulp) but otherwise it looks good. Thanks!

**Comment by barbeau** [comment]
Thanks Tony!

@mohangandhiGH could you please update the Readme with new build instructions for Gulp?

**Comment by mohangandhiGH** [comment]
@laidig I have updated Readme. Could you please review the changes.

**Comment by barbeau** [comment]
@laidig and @sheldonabrown Would you be able to review/merge this PR this week?  We're trying to wrap up a few items on the GTFS-rt validator, and this PR is blocking us finishing integration of the static validator.

**Comment by laidig** [comment]
@sheldonabrown is the one with commit access ;)

**Comment by barbeau** [comment]
Thanks Sheldon!

**Pull request merged**
