### PR TITLE
Fix #17 - Add mix-in annotation for serializing bounds

### LINKED ISSUE #17: Infinite recursion when serializing bounds
```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: java.awt.geom.Double["bounds2D"]->java.awt.geom.Double["bounds2D"]->java.awt.geom.Double["bounds2D"]->java.awt.geom.Double["bounds2D"]->java.awt.geom.Double["bounds2D"]->...

at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:658)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:541)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:644)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:541)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:644)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:541)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:644)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:541)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:644)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
...
Caused by: java.lang.StackOverflowError
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:660)
    ... 1011 more

```

### PR DESCRIPTION
**Pull request by barbeau**
* Avoids a java.lang.StackOverflowError due to infinite recursion on  java.awt.geom.Rectangle2D.Double#getBounds2D
* Add unit test for writing JSON output

Replaces PR https://github.com/conveyal/gtfs-validator/pull/39.

@mattwigway I think this should do the trick - could you please review?

### CODE REVIEW

**Comment by barbeau** [comment]
Also, FYI, it looks like Travis isn't turned on for this project in the Travis console.

**Comment by laidig** [comment]
@barbeau IIRC when I spoke with @sheldonabrown he mentioned that CI was being handled by Jenkins for this fork.

**Comment by barbeau** [comment]
@laidig I believe you're right, but Jenkins isn't integrated into the Github PR process and it's not easy for contributors to see the build status.  Also doesn't hurt to have a 2nd CI build process running on a different platform.  Travis is already configured for the project in `.travis.yml` here, so someone with push permissions for this repo just needs to flip the switch at https://travis-ci.org/ and it should go live.

**Review by mattwigway — APPROVED** [review]
This looks good to me. @landonreed  and @sheldonabrown any objections to merging this?

**Comment by landonreed** [comment]
No objections here.

**Comment by barbeau** [comment]
Thanks for the review @mattwigway and @landonreed!  Are we able to get this merged?  I'd like to wrap up integration with our gtfs-rt-validator this week.

**Comment by barbeau** [comment]
Friendly ping - @mattwigway @landonreed @abyrd or @sheldonabrown - could we get this merged so we can integrate into the gtfs-rt-validator?

**Comment by landonreed** [comment]
@barbeau, since we (Conveyal) are not actively using this library in any Conveyal projects at the moment, I would defer to @sheldonabrown on this.

**Comment by barbeau** [comment]
@landonreed @mattwigway @abyrd It seems that Conveyal's focus has shifted to [gtfs-lib](https://github.com/conveyal/gtfs-lib) instead of this project.

Given that others (specifically USF, @laidig, and @sheldonabrown with camsys) are using this gtfs-validator project and intend to contribute more to it, would you be open to shifting it to an multi-organizational account like OneBusAway (https://github.com/OneBusAway) where multiple people from different organizations could review/merge PRs?

For example, there are some static GTFS validation rules (https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/126 for one) that we'd like to add here that are important for GTFS-realtime.

**Comment by abyrd** [comment]
@barbeau that is correct, as far as I know we haven't used this library at all for quite some time, and should probably put a notice on the readme page stating this. If other people prefer to use this library I don't see any problem with moving it. I would like to understand though why this library is preferred, and what were the criteria that lead you and Camsys to choose it.

While I think the cost of duplicated effort here is low, as validator libraries have a fairly narrow scope, and there's even an advantage to having several groups of people validate the data with different approaches (see the meta-validator that recently appeared), I do wonder if it would be better if everyone just contributed validator modules to the same framework, which for Conveyal is now gtfs-lib.

**Comment by barbeau** [comment]
In our case we didn't know about gtfs-lib until after we spent time integrating gtfs-validator.  Our primary criteria for gtfs-validator was a Java-based solution that had an existing web UI.  And we saw that @laidig was actively working on his fork for use at MTA in NYC.

I'm definitely open to integrating gtfs-lib in addition to (or eventually in place of) gtfs-validator into our gtfs-rt-validator - I just opened https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/193 for this.  Given that gtfs-lib doesn't have a web UI for initial integration and our current focus, we'd probably just spit out the JSON file and build a UI for the output later.  I believe Transitland is now showing gtfs-lib in their web UI, so maybe we could grab some code from there to speed things up.

For now, though, given the existing effort we've sunk into this, I'd like to focus on quickly iterating on gtfs-validator to get some rules specific to static GTFS but necessary for good real-time data added.

**Comment by laidig** [comment]
I'd be happy to contribute to gtfs-lib (or another project that is a little less crufty than this one). A modular project is good-- I've admittedly pulled the master branch of this repo very much towards something that hits the problems we've had and not necessarily the problems others encounter.

**Comment by KiraLis39** [comment]
Проблема по-прежнему актуальна, почему так долго не удаётся решить?
Не вижу никаких решений здесь.

**Pull request merged**
