### PR TITLE
Fix #25 - Failed to require 'jquery' and 'bootstrap' modules

### LINKED ISSUE #25: Failed to require 'jquery' and 'bootstrap' modules
This is an issue in gtfs-validator-webapp module. 
when we try to browse to the server to see feed validation reports, it's throwing an error 'failed to require jquery' module. 

There is actually parameter name mismatch when calling function **require**('jquery') in index.html file. The parameter it should pass is 'components~jquery@[*latest_version*]'

### PR DESCRIPTION
**Pull request by mohangandhiGH**
modified to pass **require()** function the expected jquery and bootstrap module names

Fixes #25

### CODE REVIEW

**Comment by barbeau** [comment]
@sheldonabrown Sorry to bug you again, but would you be able to merge and cut a new release with this?  I believe it's the last item preventing us from integrating with our gtfs-realtime-validator.

**Comment by barbeau** [comment]
@sheldonabrown We believe we don't actually need a release to start using this in our gtfs-realtime-validator project, a simple merge to master branch is sufficient.  Could you please merge this and https://github.com/conveyal/gtfs-validator/pull/29?

**Comment by sheldonabrown** [comment]
Sorry Sean.  Somehow I missed the notification on this.  All set now.

**Comment by barbeau** [comment]
No problem, thanks for review/merge!

**Pull request merged**
